import org.apache.tika.sax.BodyContentHandler;
import org.xml.sax.SAXException;

public class BodyReader extends BodyContentHandler {
	
	public BodyReader(int n) {
		super (n);
	}
    @Override
    public void ignorableWhitespace(char[] ch, int start, int length)
            throws SAXException {
        // Not writing extra new lines generated by XHTMLContentHandler.
    }
}